### ISSUE TITLE
python3且安装了jwt使用报错

### ISSUE THREAD

**Issue by cwkiller** [Ch1ngg/JWTPyCrack#2]
![image](https://user-images.githubusercontent.com/19302055/81254807-bb2f8280-905e-11ea-888d-e386be4640cd.png)

**Comment by Ch1ngg** [comment]
卸载所有的jwt包
`
pip3 uninstall pyjwt
pip3 uninstall jwt
`
重新安装jwt
`
pip3 install pyjwt==1.5.3 --user -i https://pypi.douban.com/simple
`
运行
`/usr/local/bin/python3 /Users/ch1ng/Workspaces/Python/demo/hash.py -m generate -s {\"admin\":\"True\"}`
